server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.tinubu.application: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: assurance_user
    password: assurance_pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50