# Configuration du serveur
server:
  port: 8080

# Configuration de Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Configuration du logging
logging:
  level:
    root: INFO
    com.tinubu.application: DEBUG